spring:
  mvc.pathmatch.matching-strategy: ant_path_matcher
  application:
    name: dna-chronos-service
    version: 1.1.0

  cloud:
    vault:
      host: ${VAULT_HOST:localhost}
      port: ${VAULT_PORT:8200}
      scheme: ${VAULT_SCHEME:http}
      authentication: ${VAULT_AUTHENTICATION:TOKEN}
      token: ${VAULT_TOKEN:s.eCq15kV0JMi2xrcVaxDKMpZ7}
      mountpath: ${VAULT_MOUNTPATH:kv}
      vaultpath: ${VAULT_PATH:dna/chronos}
      kv:
        enabled: true

  flyway:
    enabled: ${FLYWAY_ENABLED:false}
    baseline-on-migrate: ${FLYWAY_BASELINE_ON_MIGRATE:false}
    baselineVersion: ${FLYWAY_BASELINEVERSION:0}
    schemas: ${FLYWAY_SCHEMA:public}

  jpa:
    database: POSTGRESQL
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: none

  datasource:
    hikari:
      connection-timeout: 4000
    platform: postgres
    url: ${API_DB_URL:jdbc:postgresql://localhost:65482/storage}
    username: ${API_DB_USER:storage}
    password: ${API_DB_PASS:abcf02d283e9be06ea55ba189a2a00a77d35d12a}

    driverClassName: org.postgresql.Driver

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

#  cloud:
#    stream:
#      default-binder: kafka
#      kafka:
#        binder:
#          brokers: ${NAAS_BROKER:hostXXXX:portXXXX}
#
#
#kafka:
#  centralTopic:
#    name: dnaCentralEventTopic


databricks:
  userid: ${DATABRICKS_USERID:PID4A91}
  userauth: ${DATABRICKS_USER_AUTH:xdapi900b2a3c18c0389ebec36fed74010fb2x}
  pat: ${DATABRICKS_PAT:dapi900b2a3c18c0389ebec36fed74010fb2}
  jobId: ${DATABRICKS_JOBID:880249523242944}
  powerfulMachinesJobId: ${DATABRICKS_POWERFULMACHINESJOBID:93437937072820}
  defaultConfigYml: ${DATABRICKS_DEFAULTCONFIGYML_PATH:chronos-core/objects?prefix=configs/}
  uri:
    base: ${DATABRICKS_BASE_URI:https://adb-2518131549527911.11.azuredatabricks.net}
    runnow: ${DATABRICKS_RUNNOW_URI:/api/2.1/jobs/run-now}
    deleterun: ${DATABRICKS_DELETERUN_URI:/api/2.1/jobs/runs/delete}
    getrun: ${DATABRICKS_GETRUN_URI:/api/2.1/jobs/runs/get}
    jobrunlist: ${DATABRICKS_JOBRUNLIST_URI:/api/2.1/jobs/get}
    jobrunoutput: ${DATABRICKS_GETRUNOUTPUT_URI:/api/2.1/jobs/runs/get-output}

dna:
  uri: ${DNA_URI:https://dev.dna.app.corpintra.net/}
  dnaAuthEnable: ${DNA_AUTH_ENABLE:true}


jwt:
  secret:
    key: ${JWT_SECRET_KEY:oeRaYY7Wo24sDqKSX3IM9ASGmdGPmkTd9jo1QTy4b7P9Ze5_9hKolVX8xNrQDcNRfVEdTZNOuOyqEGhXEbdJI-ZQ19k_o9MI0y3eZN2lp9jow55FfXMiINEdt1XR85VipRLSOkT6kSpzs2x-jbLDiz9iFVzkd81YKxMgPA7VfZeQUm4n-mOmnWMaVX30zGFU4L3oPBctYKkl4dYfqYWqRNfrgPJVi5DGFjywgxx0ASEiJHtV72paI3fDR2XwlSkyhhmY-ICjCRmsJN4fX1pdoL8a18-aQrvyu4j0Os6dVPYIoPvvY0SAZtWYKHfM15g7A3HD4cVREf9cUsprCRK93w}

server:
  port: 8989

storage.uri : ${STORAGE_API_BASE_URL:https://storage.dev.dna.app.corpintra.net/}

#Cors Filter origin Domains
allowedCorsOriginPatternUrl: ${CORS_ORIGIN_URL:http://*}

swagger.headers.authorization.token: ${SWAGGER_HEADER_AUTH:XXXXXX}
swagger.headers.authorization.appId: ${SWAGGER_HEADER_AUTH_APPID:XXXXXX}
swagger.headers.authorization.apiKey: ${SWAGGER_HEADER_AUTH_APPKEY:XXXXXX}
management.endpoints.web.exposure.include: loggers,health
management.endpoint.loggers.enabled: true
management.endpoint.health.probes.enabled: true
management.endpoint.health.show-details: always

proxy:
  port: ${CUSTOMPROXY_PORT:3128}
  host: ${CUSTOMPROXY_HOST:security-proxy.emea.svc.corpintra.net}

logging:
  service:
    environment: ${LOGGING_ENVIRONMENT:DEV}
    path: ${LOGGING_PATH:/var/log}
  level:
    com:
      daimler:
        data:
          application: INFO
          controller.ItsmmGameController: DEBUG
    org.springframework.boot.autoconfigure.logging: INFO
    com.daimler.data.application.logging.ApplicationLoggingAspect: DEBUG
    org:
      springframework:
        web:
          client:
            RestTemplate: INFO
      hibernate:
        type:
          descriptor:
            sql: ERROR
