spring:
  mvc.pathmatch.matching-strategy: ant_path_matcher
  application:
    name: trinio-registry-service
    version: 1.1.1

dna:
  uri: ${DNA_URI:XXXXXX}
  dnaAuthEnable: ${DNA_AUTH_ENABLE:false}
  

server:
  port: 7575

#Cors Filter origin Domains  
allowedCorsOriginPatternUrl: ${CORS_ORIGIN_URL:http://*}
  
jwt:
  secret:
    key: ${JWT_SECRET_KEY:XXXXXX}
      
minio:
  baseUri: ${MINIO_BASEURI:http://xxxxx}
  accessKey: ${MINIO_ACCESSKEY:XXXXX}
  secretKey: ${MINIO_SECRETKEY:XXXXX}

trino:
  uri: ${TRINO_BASEURI:http://xxxxx}
  user: ${TRINO_USER:XXXXX}
  password: ${TRINO_PASSWORD:XXXXX}
  ssl: ${TRINO_SSL:true}
  sslverification: ${TRINO_SSLVERIFICATION:NONE}
  catalog: ${TRINO_CATALOG:XXXXX}
  hadoop.remoteUser: ${TRINO_UNIX_HADOOP_REMOTEUSER:spring}
   
swagger.headers.authorization.token: ${SWAGGER_HEADER_AUTH:XXXXXX}
management.endpoints.web.exposure.include: loggers,health
management.endpoint.loggers.enabled: true
management.endpoint.health.probes.enabled: true
management.endpoint.health.show-details: always

logging:
  service:
    environment: ${LOGGING_ENVIRONMENT:DEV}
    path: ${LOGGING_PATH:/var/log}
  level:
    com:
      daimler:
        data: INFO
    org.springframework.boot.autoconfigure.logging: INFO
    org:
      springframework:
        web:
          client:
            RestTemplate: INFO
