# Default values for storage-be.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: storage
#Add new env as array value with name/value field. Keep one tab indentation.
envs:
  - name: MAX_FILE_SIZE
    value: 3000MB
  - name: MAX_REQUEST_SIZE
    value: 3000MB
  - name: VAULT_HOST
    value: vault.vault.svc.cluster.local
  - name: VAULT_PORT
    value: "8200"         
  - name: VAULT_SCHEME
    value: http
  - name: VAULT_AUTHENTICATION
    value: TOKEN
  - name: VAULT_TOKEN
    valueFrom:
      secretKeyRef:
        key: vaultToken
        name: storage-be
  - name: VAULT_MOUNTPATH
    value: kv
  - name: VAULT_PATH
    value: dna/minio  
  - name: DNA_URI
    value: http://dna-app-backend-service.dna.svc.cluster.local:80
  - name: DNA_AUTH_ENABLE
    value: "true"  
  - name: JWT_SECRET_KEY
    valueFrom:
      secretKeyRef:
        key: jwt.secret.key
        name: storage-be
  - name: CORS_ORIGIN_URL
    value: "" 
  - name: MINIO_ENDPOINT
    value: http://my-release-minio.minio.svc.cluster.local:9000
  - name: MINIO_CLIENT_API
    value: ""
  - name: MINIO_ROOT_USER
    valueFrom:
      secretKeyRef:
        key: minioAccessKey
        name: storage-be  
  - name: MINIO_ROOT_PASSWORD
    valueFrom:
      secretKeyRef:
        key: minioSecretKey
        name: storage-be   
  - name: MINIO_POLICY_VERSION
    value: "2012-10-17"   
  - name: LOGGING_ENVIRONMENT
    value: DEV   
  - name: LOGGING_PATH
    value: /var/log    
  - name: ATTACHMENT_MALWARE_SCAN
    value: "false"  
  - name: MALWARE_SCANNER_URI
    value: ""
  - name: MALWARE_SCANNER_APP_ID
    valueFrom:
      secretKeyRef:
        key: malwareApiId
        name: storage-be  
  - name: MALWARE_SCANNER_API_KEY
    valueFrom:
      secretKeyRef:
        key: malwareApiKey
        name: storage-be
  - name: STORAGE_TERMS_OF_USE_URL
    value: ""          
  - name: DATAIKU_PROD_URI
    value: "https://***REMOVED***/public/api"    
  - name: DATAIKU_PROD_API_KEY
    valueFrom:
      secretKeyRef:
        key: dataikuProdApiKey
        name: storage-be
  - name: DATAIKU_TRAINING_URI
    value: "https://***REMOVED***/public/api"
  - name: DATAIKU_TRAINING_API_KEY
    valueFrom:
      secretKeyRef:
        key: dataikuTrainingApiKey
        name: storage-be  
  - name: FLYWAY_ENABLED
    value: "true"
  - name: FLYWAY_BASELINE_ON_MIGRATE
    value: "true"
  - name: FLYWAY_BASELINEVERSION
    value: "0"  
  - name: FLYWAY_SCHEMA
    value: "public"                                

secret:
  - key: vaultToken
    value: ""
  - key: jwt.secret.key 
    value: ""
  - key: minioAccessKey 
    value: ""
  - key: minioSecretKey
    value: ""
  - key: malwareApiId 
    value: ""
  - key: malwareApiKey
    value: ""   
  - key: dataikuProdApiKey
    value: ""
  - key: dataikuTrainingApiKey
    value: ""       

replicaCount: 1

image:
  repository: ""
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets:
  - name: harbor-pull-secret
nameOverride: ""
fullnameOverride: "storage-be"

podSecurityContext: 
  runAsUser: 1000

containerPort: 7175
service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    traefik.frontend.rule.type: PathPrefix
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: ""
  hosts:
    - host: chart-example.local
      paths:
        - path: /storage/api
          pathType: Prefix
        - path: /storage/swagger-ui.html
          pathType: Prefix
        - path: /storage/swagger-resources
          pathType: Prefix
        - path: /storage/v2/api-docs
          pathType: Prefix
        - path: /storage/webjars
          pathType: Prefix
  tls:
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
    - hosts:
      - chart-example.local
      secretName: my-tls-secret

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

## Inject the application environment variable from vault service
# If you enable vault injector, the environment variables specified above will be will be override from vault
vaultInjector:
  enable: false
  annotations:
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/role: 'dna'
    vault.hashicorp.com/agent-pre-populate-only: 'true'
    vault.hashicorp.com/agent-inject-secret-envvar: 'kv/dna/kubernetesSecret/storageService'
    vault.hashicorp.com/agent-inject-template-envvar: | 
      {{- with secret "kv/dna/kubernetesSecret/storageService" -}}
        {{- range $k, $v := .Data.data }}
            export {{ $k }}="{{ $v }}"
        {{- end }}
      {{- end }}
      {{- with secret "kv/dna/kubernetesSecret/minio" -}}
        {{- range $k, $v := .Data.data }}
            export {{ $k }}="{{ $v }}"
        {{- end }}
      {{- end }}        
  saName: "default"
  jarName: "storage-lib*.jar"