annotations:
  artifacthub.io/changes: |
    - "[Added]: Add priorityClassName to notifications controller"
apiVersion: v2
appVersion: v2.4.11
dependencies:
- condition: redis-ha.enabled
  name: redis-ha
  repository: https://dandydeveloper.github.io/charts/
  version: 4.22.1
description: A Helm chart for Argo CD, a declarative, GitOps continuous delivery tool
  for Kubernetes.
home: https://github.com/argoproj/argo-helm
icon: https://argo-cd.readthedocs.io/en/stable/assets/logo.png
keywords:
- argoproj
- argocd
- gitops
maintainers:
- name: argoproj
  url: https://argoproj.github.io/
name: argo-cd
version: 5.4.2
