# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: {{ .Chart.Name }}-db-dir
#   namespace: {{ .Values.namespace }}
#   labels:
#     name: {{ .Chart.Name }}
# spec:
#   storageClassName: {{ .Values.Storage.storageClass }}
#   accessModes:
#     - {{.Values.Storage.accessModes }}
#   resources:
#     requests:
#       storage: {{ .Values.Storage.size | quote }}
  
