apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Chart.Name }}-backend-web-allow-netpol
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      name: {{ .Chart.Name }}-backend
  ingress:
    - ports:
      - port: {{ .Values.backend.containerPort }}
    - podSelector:
          matchLabels:
            app: dna-kong-gw-kong
        namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: kong
  policyTypes:
    - Ingress      