version: "2.1"
services:
  result-frontend:
    image: ${IMAGE_RESULT_FRONTEND:-vardhandevalla/okta-app-frontend-pi2:v2.0}
    build:
      context: ../packages/frontend/
      dockerfile: $PWD/dockerfiles/app/result-frontend.Dockerfile
    environment:
      - "PROJECTSMO_BACKEND_HOST=result-backend"
    ports:
      - "8080:80"

  result-backend:
    image: ${IMAGE_RESULT_BACKEND:-dna_backend}
    build:
      context: ../packages/backend/
      dockerfile: $PWD/dockerfiles/app/result-backend.Dockerfile

  
