apiVersion: v1
appVersion: 5.14.0
description: Neo4j is the world's leading graph database
home: https://www.neo4j.com
icon: http://info.neo4j.com/rs/773-GON-065/images/neo4j_logo.png
keywords:
- graph
- database
- cypher
maintainers:
- email: bledi.feshti@neotechnology.com
  name: bfeshti
- email: harshit.singhvi@neotechnology.com
  name: harshitsinghvi22
name: neo4j
sources:
- https://github.com/neo4j/neo4j
- https://github.com/neo4j/docker-neo4j
version: 5.14.0
