{{- if not .Values.vaultInjector.enable }}  
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  minio.secretkey: {{ .Values.secret.minioSecretKey | b64enc | quote }}
  trino.password: {{ .Values.secret.trinoPassword | b64enc | quote }}
  jwt.secret.key: {{ .Values.secret.jwtKey | b64enc | quote }}
{{- end }}