{{- $clusterEnabled := eq (include "neo4j.isClusterEnabled" .) "true" }}
{{- if or (and $clusterEnabled (empty $.Values.podSpec.serviceAccountName)) $.Values.analytics.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: {{ include "neo4j.fullname" . }}
  labels:
    app: "{{ template "neo4j.name" $ }}"
    {{- include "neo4j.labels" $.Values.neo4j | indent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: "{{ include "neo4j.fullname" . }}-service-reader"
  labels:
    app: "{{ template "neo4j.name" $ }}"
    {{- include "neo4j.labels" $.Values.neo4j | indent 4 }}
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["services", "endpoints"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: "{{ .Release.Namespace }}"
  name: "{{ include "neo4j.fullname" . }}-service-binding"
  labels:
    app: "{{ template "neo4j.name" $ }}"
    {{- include "neo4j.labels" $.Values.neo4j | indent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "neo4j.fullname" . }}
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role # this must be Role or ClusterRole
  name: {{ include "neo4j.fullname" . }}-service-reader # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
{{- end }}
