{{- $clusterEnabled := eq (include "neo4j.isClusterEnabled" .) "true" }}
{{- $ignored := required "neo4j.name is required" .Values.neo4j.name }}
{{- $isLoadBalancerEnabled := index .Values.services.neo4j.enabled }}
{{- $loadBalancer := list -}}
{{- $loadBalancerExists := false -}}

{{- if and (not .Values.disableLookups) ($clusterEnabled) -}}
  {{- $loadBalancer = (lookup "v1" "Service" .Release.Namespace (printf "%s-lb-neo4j" (include "neo4j.name" $))) }}
  {{- $loadBalancerExists = $loadBalancer | all }}
{{- end -}}

{{- if and $loadBalancerExists $isLoadBalancerEnabled -}}
  {{- $loadBalancerSelector :=  $loadBalancer.spec.selector -}}
  {{- if hasKey $loadBalancerSelector "helm.neo4j.com/clustering" -}}
    {{- if eq (get $loadBalancerSelector "helm.neo4j.com/clustering") "false" -}}
      {{- if eq (get $loadBalancerSelector "app") (include "neo4j.name" $) -}}
        {{- if not .Release.IsUpgrade -}}
          {{ fail (printf "%s %v %s" "A Neo4j installation already exists in this namespace with the name" .Values.neo4j.name "Please use a different neo4j name using --set neo4j.name") }}
        {{- end -}}
      {{- end -}}
    {{- end -}}
  {{- end -}}
{{- end -}}

{{- if and (not $loadBalancerExists) ($isLoadBalancerEnabled) -}}
{{- $defaultSpec := include "neo4j.services.neo4j.defaultSpec" . | fromYaml }}
{{- $spec := get $defaultSpec .Values.services.neo4j.spec.type | merge .Values.services.neo4j.spec  }}
# Service for applications that need access to neo4j
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "neo4j.name" $ }}-lb-neo4j"
  namespace: "{{ .Release.Namespace }}"
  labels:
    helm.neo4j.com/neo4j.name: "{{ template "neo4j.name" $ }}"
    app: "{{ template "neo4j.name" . }}"
    helm.neo4j.com/service: "neo4j"
    {{- include "neo4j.labels" .Values.neo4j | indent 4 }}
  annotations:
  {{- if $clusterEnabled }}
    helm.sh/resource-policy: keep
  {{- end }}
  {{- range $key, $value := .Values.services.neo4j.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  {{- if $.Values.services.neo4j.multiCluster }}
  publishNotReadyAddresses: true
  {{- end }}
  type: "{{ $spec.type | required "service type must be specified" }}"
  {{- omit $spec "type" "ports" "selector" | include "neo4j.services.extraSpec"  | nindent 2 }}
  ports:
    {{- with .Values.services.neo4j.ports }}
    {{- if .http.enabled }}
    - protocol: TCP
      port: {{ .http.port | default 7474 }}
      targetPort: {{ .http.targetPort | default 7474 }}
      name: {{ .http.name | default "http" }}
    {{- end }}
    {{- if .https.enabled }}
    - protocol: TCP
      port: {{ .https.port | default 7473 }}
      targetPort: {{ .https.targetPort | default 7473 }}
      name: {{ .https.name | default "https" }}
    {{- end }}
    {{- if .bolt.enabled }}
    - protocol: TCP
      port: {{ .bolt.port | default 7687 }}
      targetPort: {{ .bolt.targetPort | default 7687 }}
      name: {{ .bolt.name | default "tcp-bolt" }}
    {{- end }}
    {{ with .backup }}
    {{- if .enabled }}
    - protocol: TCP
      port: {{ .port | default 6362 }}
      targetPort: {{ .targetPort | default 6362 }}
      name: {{ .name | default "tcp-backup" }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{/* this condition opens internal ports only when multi-k8s-cluster is enabled */}}
    {{- if .Values.services.neo4j.multiCluster }}
    - name: tcp-boltrouting
      protocol: TCP
      port: 7688
      targetPort: 7688
    - name: tcp-discovery
      protocol: TCP
      port: 5000
      targetPort: 5000
    - name: tcp-raft
      protocol: TCP
      port: 7000
      targetPort: 7000
    - name: tcp-tx
      protocol: TCP
      port: 6000
      targetPort: 6000
    {{- end }}
  selector:
    app: "{{ template "neo4j.name" . }}"
    {{- if $clusterEnabled }}
    helm.neo4j.com/clustering: "true"
    {{- else }}
    helm.neo4j.com/clustering: "false"
    {{- end }}
    {{- with .Values.services.neo4j.selector }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
{{- end -}}
