annotations:
  category: Database
apiVersion: v2
appVersion: 8.0.30
dependencies:
  - name: common
    repository: file://charts/common
    # tags:
    #   - bitnami-common
    version: 1.16.1
description: MySQL is a fast, reliable, scalable, and easy to use open source relational database system. Designed to handle mission-critical, heavy-load production applications.
home: https://github.com/bitnami/charts/tree/master/bitnami/mysql
icon: https://bitnami.com/assets/stacks/mysql/img/mysql-stack-220x234.png
keywords:
  - mysql
  - database
  - sql
  - cluster
  - high availability
maintainers:
  - name: Bitnami
    url: https://github.com/bitnami/charts
name: mysql
sources:
  - https://github.com/bitnami/containers/tree/main/bitnami/mysql
  - https://mysql.com
version: 9.2.6
