{{- if not .Values.vaultInjector.enable }}  
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.backend.secrets.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  onapi.basicauth.token: {{ .Values.app.backend.secrets.onapiBasicAuthToken | b64enc  | quote }}
  vault.root.token: {{ .Values.app.vault.secret.rootToken | b64enc | quote }}
  jwt.secret.key: {{ .Values.app.backend.secrets.jwtSecretKey | b64enc | quote }}
  postgres.app.username: {{ .Values.app.backend.secrets.appDBUserName | b64enc | quote }}
  postgres.app.password: {{ .Values.app.backend.secrets.appDBPassword | b64enc | quote }}
{{- end }}  