apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-frontend-configmap
  namespace: {{ .Values.namespace }}
data:
  nginx.conf: |
        worker_processes  1;
        error_log         "/opt/bitnami/nginx/logs/error.log";
        pid               "/opt/bitnami/nginx/tmp/nginx.pid";

        events {
          worker_connections  1024;
        }

        http {
            include       /opt/bitnami/nginx/conf/mime.types;
            default_type  application/octet-stream;
            log_format    main '$remote_addr - $remote_user [$time_local] '
                              '"$request" $status  $body_bytes_sent "$http_referer" '
                              '"$http_user_agent" "$http_x_forwarded_for"';
            access_log    "/opt/bitnami/nginx/logs/access.log";
            add_header    X-Frame-Options SAMEORIGIN;
            add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

            client_body_temp_path  "/opt/bitnami/nginx/tmp/client_body" 1 2;
            proxy_temp_path        "/opt/bitnami/nginx/tmp/proxy" 1 2;
            fastcgi_temp_path      "/opt/bitnami/nginx/tmp/fastcgi" 1 2;
            scgi_temp_path         "/opt/bitnami/nginx/tmp/scgi" 1 2;
            uwsgi_temp_path        "/opt/bitnami/nginx/tmp/uwsgi" 1 2;

            sendfile           on;
            tcp_nopush         on;
            tcp_nodelay        off;
            gzip               on;
            gzip_comp_level    5;
            gzip_min_length    256;
            gzip_vary          on;
            gzip_proxied       any;
            gzip_types         application/atom+xml application/vnd.ms-fontobject application/x-font-ttf application/x-web-app-manifest+json application/xhtml+xml font/opentype image/svg+xml image/x-icon text/x-component application/javascript application/json text/plain text/css application/x-javascript text/xml application/xml application/xml+rss text/javascript;
            keepalive_timeout  65;
            ssl_protocols      TLSv1 TLSv1.1 TLSv1.2;

            include  "/opt/bitnami/nginx/conf/server_blocks/*.conf";
            client_max_body_size 4G;

          server {
            listen  3000;
            add_header Referrer-Policy 'strict-origin-when-cross-origin';

            resolver kube-dns.kube-system.svc.cluster.local valid=10s;

            set $backend {{ .Values.appFrontend.ngnix.backend | quote }};

            set $avscan_mgw_server {{ .Values.appFrontend.ngnix.avscanMgwServer | quote }};

            set $clamav {{ .Values.appFrontend.ngnix.clamav | quote }};

            root /usr/share/nginx/html;
            index index.htm index.html;
            try_files $uri $uri/ /index.html;

            location / {
              add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
              add_header Cache-Control "no-store, no-cache, must-revalidate";
              ssi on;
            }
            location ~ .remoteEntry.js$ {
              expires -1;
              add_header 'Cache-Control' 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
            }

            location ~ .config.js$ {
              expires -1;
              add_header 'Cache-Control' 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
            }
            # For One-API
            # location ^~ /malware-scan {
            #   proxy_set_header X-Real-IP $remote_addr;
            #   proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            #   proxy_set_header X-NginX-Proxy true;
            #   proxy_pass https://$avscan_mgw_server;
            #   proxy_ssl_session_reuse off;
            #   proxy_set_header Host $avscan_mgw_server;
            #   proxy_redirect off;
            # }
            
            location ~* \.(?:jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc|ttf|eot|woff)$ {
              expires 1M;
              access_log "/opt/bitnami/nginx/logs/static.log";
              add_header Cache-Control "public";
            }

            location ~ ^.+\..+$ {
                try_files $uri =404;
            }

            location ^~ /api {
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-NginX-Proxy true;
              proxy_pass $backend;
              proxy_ssl_session_reuse off;
              proxy_set_header Host $http_host;
              proxy_redirect off;
            }

            location ^~ /avscan {
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-NginX-Proxy true;
              proxy_pass $clamav;
              proxy_ssl_session_reuse off;
              proxy_set_header Host $http_host;
              proxy_redirect off; # note the trailing slash here, it matters!
              rewrite /avscan(.*) $1 break;
            }

            location /inject-environment {
              default_type application/json;
              return 200 '<script type="text/javascript">window["INJECTED_ENVIRONMENT"]={OIDC_DISABLED: false};</script>';
            }
          }
        }
  {{- if not .Values.vaultInjector.enable }}  
  config.js: |
    {{ .Values.configJs | nindent 8 }}
  {{- end }}
