apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "storage-be.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      {{- include "storage-be.selectorLabels" . | nindent 8 }} 
  ingress:      
    - from:      
      - podSelector:
          matchLabels:
            app.kubernetes.io/instance: chronos-backend
            app.kubernetes.io/name: chronos-be
        namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: chronos
      - ports:
          - port: {{ .Values.containerPort }}           
  
  policyTypes:
    - Ingress    
---
