apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "authenticator-service.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "authenticator-service.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "authenticator-service.selectorLabels" . | nindent 8 }}
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: kong
      - podSelector:
          matchLabels:
            app.kubernetes.io/instance: code-server-be
            app.kubernetes.io/name: code-server-backend
        namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: code-server             
  policyTypes:
    - Ingress
