# Default values for frontend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: dna
imagePullSecret: 
  name: harbor-pull-secrets
  key: "docker-config"
ingress:
  enabled: true
  namespace: ingress
  host: "ingress-host"
  lbIP: ""
  
  annotations:
    traefik.frontend.rule.type: PathPrefix
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: ""

probes:
  initialDelaySeconds: 30
  timeoutSeconds: 10
  periodSeconds: 10
  failureThreshold: 3

  readinessProbe:
    path: /
    port: 3000

appFrontend:
  replicaCount: 1
  image: dna/app-frontend
  config: 
    oidcDisabled: true
    oidcProvider: INTERNAL
    apiBaseUrl: api
    jupyterNotebookUrl: ""
    jupyterNotebookOidcPopUpUrl: ""
    dataikuLiveAppUrl: ""
    dataikuTrainingAppUrl: ""
    oauth2TokenUrl: ""
    oauth2AuthUrl: ""
    oauth2RevokeUrl: ""
    oauth2LogoutUrl: ""
    oauth2IntrospectionUrl: ""
    oauth2UserInfoUrl: ""
    frontendClientid: ""
    redirectUrls: ""
    swaggerUiUrl: ""
    dataikuFerretUrl: ""
    mlPipelineUrl: ""
    appNameHeader: ""
    appNameHome: ""
    contactUsHtml: <div><p>There could be many places where you may need our help, and we are happy to support you. <br /> Please add your communication channels links here</p></div>
    brandLogoUrl: /images/branding/logo-brand.png
    appLogoUrl: /images/branding/logo-app.png
    enableInternalUserInfo: true
    enableDataCompliance: true
    enabledReports: false
    enableJupyterWorkspace: false
    enableDataikuWorkspace: false
    enableMalwareService: false
    enableDataPipelineService: false
    enableStorageService: false
    storageMFEAppURL: http://localhost:8083
    enablePipelineService: false
    enabledMlPipelineService: false
    enableMalwareApiInfo: false
    enableNotification: false
    companyName: XYZ
    backendHost: dna-app-backend-service
    dataPipelinesApiUrl: ""
    dataPipelinesAppUrl: ""
    notificationApiUrl: ""
    dashboardApiUrl: ""
    storageApiUrl: ""

  ngnix:
    backend: http://dna-app-backend-service.dna.svc.cluster.local:80
    # jupyServer: http://proxy-public:8000
    grafanaServer: http://i3-monitoring-grafana.i3-monitoring.svc.cluster.local:80
    avscanMgwServer: http://dna-microgateway.clamav.svc.cluster.local:80
