# Default values for frontend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: dna
imagePullSecret: 
  name: harbor-pull-secrets
  key: "docker-config"
ingress:
  enabled: true
  namespace: ingress
  host: "ingress-host"
  lbIP: ""
  
  annotations:
    traefik.frontend.rule.type: PathPrefix
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    cert-manager.io/cluster-issuer: ""

configJs: |
    window["INJECTED_ENVIRONMENT"]={
      OIDC_DISABLED: "false",
      API_BASEURL: "api",
      STORAGE_API_BASEURL: "http://localhost:7175/storage/api",
      DNA_COMPANY_NAME: "Company_Name",
      DNA_APPNAME_HEADER: "DnA App",
      DNA_APPNAME_HOME: "Data and Analytics",
      DNA_CONTACTUS_HTML: "<div><p>There could be many places where you may need our help, and we are happy to support you. <br /> Please add your communication channels links here</p></div>",
      DNA_BRAND_LOGO_URL: "/images/branding/logo-brand.png",
      DNA_APP_LOGO_URL: "/images/branding/logo-app.png",
      OIDC_PROVIDER: "OKTA",
      CLIENT_IDS: "YOUR_CLIENT_ID",
      REDIRECT_URLS: "YOUR_OKTA_REDIRECT_URL",
      OAUTH2_AUTH_URL: "https://YOUR_OKTA_DOMAIN.okta.com/oauth2/v1/authorize",
      OAUTH2_LOGOUT_URL: "https://YOUR_OKTA_DOMAIN.okta.com/oauth2/v1/logout",
      OAUTH2_REVOKE_URL: "https://YOUR_OKTA_DOMAIN.okta.com/oauth2/v1/revoke",
      OAUTH2_TOKEN_URL: "https://YOUR_OKTA_DOMAIN.okta.com/oauth2/v1/token",
      ENABLE_INTERNAL_USER_INFO: "false",
      ENABLE_DATA_COMPLIANCE: "false",
      ENABLE_JUPYTER_WORKSPACE: "false",
      JUPYTER_NOTEBOOK_URL: "YOUR_NOTEBOOK_URL",
      JUPYTER_NOTEBOOK_OIDC_POPUP_URL: "YOUR_NOTEBOOK_AUTH_REDIRECT_URL",
      JUPYTER_NOTEBOOK_OIDC_POPUP_WAIT_TIME: "5000",
      ENABLE_DATAIKU_WORKSPACE: "false",
      DATAIKU_LIVE_APP_URL: "YOUR_DATAIKU_LIVE_URL",
      DATAIKU_TRAINING_APP_URL: "YOUR_DATAIKU_TRAINING_URL",
      DATAIKU_FERRET_URL: "YOUR_DATAIKU_FERRET_URL",
      ENABLE_MALWARE_SCAN_SERVICE: "true",
      MALWARE_SCAN_SWAGGER_UI_URL: "YOUR_MALWARE_SCAN_SWAGGER_UI_URL",
      ENABLE_MALWARE_SCAN_ONEAPI_INFO: "false",
      ENABLE_DATA_PIPELINE_SERVICE: "true",
      ENABLE_MY_MODEL_REGISTRY_SERVICE: "false",
      ENABLE_STORAGE_SERVICE: "true",
      CONTAINER_APP_URL: 'http://localhost:9090',
      STORAGE_MFE_APP_URL: "http://localhost:8083",
      ENABLE_REPORTS: "true",
      ENABLE_ML_PIPELINE_SERVICE: "true",
      ENABLE_NOTIFICATION: "true",
      ML_PIPELINE_URL: "YOUR_ML_PIPELINE_URL",
      MODEL_REGISTRY_API_BASEURL = "YOUR_MODEL_REGISTRY_API_BASEURL",
      INTERNAL_USER_TEAMS_INFO='(Recommended to use Short ID. To find Short ID use <a href="YOUR_TEAMS_INFO_URL" target="_blank" rel="noreferrer noopener">Teams</a>)'
      ENABLE_DATA_PRODUCT: "true",
      DATA_PRODUCT_MFE_APP_URL:"http://localhost:8084",
      ENABLE_SAP_ANALYTICS_CLOUD: "false",
      SAP_ANALYTICS_CLOUD_URL: "YOUR_SAP_ANALYTICS_CLOUD_URL",
      ENABLE_APP_FEEDBACK: "false",
      APP_FEEDBACK_EXTERNAL_URL: "YOUR_APP_FEEDBACK_EXTERNAL_URL",
      ENABLE_CHRONOS_FORECASTING_SERVICE: "false",
      CHRONOS_MFE_APP_URL:"http://localhost:8085"
    };

    window["STORAGE_INJECTED_ENVIRONMENT"]={
      CONTAINER_APP_URL: "http://localhost:9090",
      API_BASEURL: "http://localhost:7171/api",
      STORAGE_API_BASEURL: "http://localhost:7175/storage/api",
      TOU_HTML: "<div>I agree to <a href=\"#\" target=\"_blank\" rel=\"noopener noreferrer\">terms of use</a></div>", 
      ENABLE_DATA_CLASSIFICATION_SECRET: false
    };

    window["DATA_PRODUCT_INJECTED_ENVIRONMENT"]={
        CONTAINER_APP_URL: "http://localhost:9090",
        API_BASEURL: "http://localhost:7171/api",
        DATA_PRODUCT_API_BASEURL: "",
        DATA_GOVERNANCE_HTML_FOR_CHINA_DATA: "<p>If yes, and due to the complexity of corresponding Data Governance requirements, we recommend you reach out to us at the <a href=\"#\" target=\"_blank\" rel=\"noopener noreferrer\"> Data Governance Office FM </a> directly.</p>"
        DATA_PRODUCT_TOU_HTML: '<div>I agree to <a href="#" target="_blank" rel="noopener noreferrer">terms of use</a></div>'
    };

    window["CHRONOS_INJECTED_ENVIRONMENT"]={
      CONTAINER_APP_URL: "http://localhost:9090",
      API_BASEURL: "http://localhost:7171/api",
      CHRONOS_API_BASEURL: "",
    };
    
probes:
  initialDelaySeconds: 30
  timeoutSeconds: 10
  periodSeconds: 10
  failureThreshold: 3

  readinessProbe:
    path: /
    port: 3000

appFrontend:
  replicaCount: 1
  image: dna/app-frontend
  ngnix:
    backend: http://dna-app-backend-service.dna.svc.cluster.local:80
    avscanMgwServer: http://dna-microgateway.clamav.svc.cluster.local:80
    clamav: http://clamav-rest-service.clamav.svc.cluster.local:8181    

## Inject the application environment variable from vault service
# If you enable vault injector, the environment variables specified above will be will be override from vault
vaultInjector:
  enable: false
  annotations:
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/role: 'dna'
    vault.hashicorp.com/agent-pre-populate-only: 'true'
    vault.hashicorp.com/agent-inject-secret-configjs: 'kv/dna/kubernetesSecret/dnaFrontend'
    vault.hashicorp.com/agent-inject-file-configjs: "config.js"
    vault.hashicorp.com/agent-inject-template-configjs: | 
      {{- with secret "kv/dna/kubernetesSecret/dnaFrontend" -}}
          window["INJECTED_ENVIRONMENT"]={
          {{- range $k, $v := .Data.data }}
          {{- if or (eq $v "true") (eq $v "false") (regexMatch "^[0-9]+$" $v) }}
                  {{ $k }}:{{ $v }},
          {{ else }}
                  {{ $k }}:'{{ $v }}',
          {{- end }}
          {{- end }}
              };
      {{- end }}
      {{- with secret "kv/dna/kubernetesSecret/storageMFE" -}}
          window["STORAGE_INJECTED_ENVIRONMENT"]={
          {{- range $k, $v := .Data.data }}
          {{- if or (eq $v "true") (eq $v "false") (regexMatch "^[0-9]+$" $v) }}
                  {{ $k }}:{{ $v }},
          {{ else }}
                  {{ $k }}:'{{ $v }}',
          {{- end }}
          {{- end }}
              };
      {{- end }}
      {{- with secret "kv/dna/kubernetesSecret/dataProductMFE" -}}
          window["DATA_PRODUCT_INJECTED_ENVIRONMENT"]={
          {{- range $k, $v := .Data.data }}
          {{- if or (eq $v "true") (eq $v "false") (regexMatch "^[0-9]+$" $v) }}
                  {{ $k }}:{{ $v }},
          {{ else }}
                  {{ $k }}:'{{ $v }}',
          {{- end }}
          {{- end }}
              };
      {{- end }}  
  saName: "default"
